/// @author Olivier Roulet-Dubonnet 
/// @email olivier@sintef.no 
/// @brief Opc Ua Binary. 
/// @license GNU LGPL
///
/// Distributed under the GNU LGPL License
/// (See accompanying file LICENSE or copy at
/// http://www.gnu.org/licenses/lgpl.html)
///

#pragma once

#include <opc/ua/protocol/protocol_auto.h>
#include <opc/ua/protocol/variable_access_level.h>

#include <opc/ua/protocol/binary/stream.h> //FIXME move out
#include <opc/ua/protocol/input_from_buffer.h> //FIXME move out
#include <ostream>
#include <iostream>
#include <vector>

//This file is mean to override autogenerated struct to add constructors or interval members we want
namespace OpcUa
{
  inline ReadValueId MakeReadValueId(NodeId node, AttributeID attr) 
  {
    ReadValueId rv;
    rv.TypeId = node;
    rv.AttributeId = attr;
    return rv;
  }

}
