// DO NOT EDIT THIS FILE!
// It is automatically generated from opcfoundation.org schemas.
//

/// @brief Opc Ua Binary.
/// @license GNU LGPL
///
/// Distributed under the GNU LGPL License
/// (See accompanying file LICENSE or copy at
/// http://www.gnu.org/licenses/lgpl.html)
///

#pragma once

#include <opc/ua/protocol/enum_auto.h>

namespace OpcUa
{


  // forward declare structs that are not autogenerated
  struct NodeId;
  struct ExpandedNodeId;
  struct Variant;
  struct QualifiedName;
  struct DataValue;
  struct LocalizedText;
  struct ByteString;

    // XmlElement
    struct XmlElement 
    {
         int32_t Length;
         std::vector<char> Value;
    };

    // DiagnosticInfo
    struct DiagnosticInfo 
    {
         uint8_t Encoding;
         int32_t SymbolicId;
         int32_t NamespaceURI;
         int32_t LocalizedText;
         std::string AdditionalInfo;
         StatusCode InnerStatusCode;
         DiagnosticInfo InnerDiagnosticInfo;
    };

    // ExtensionObject
    struct ExtensionObject 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<uint8_t> Body;
    };

    // ua:ExtensionObject
    struct Argument 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string Name;
         NodeId DataType;
         int32_t ValueRank;
         std::vector<uint32_t> ArrayDimensions;
         LocalizedText Description;
    };

    // ua:ExtensionObject
    struct EnumValueType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         int64_t Value;
         LocalizedText DisplayName;
         LocalizedText Description;
    };

    struct TimeZoneDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         int16_t Offset;
         bool DaylightSavingInOffset;
    };

    // ua:ExtensionObject
    struct ApplicationDescription 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string ApplicationUri;
         std::string ProductUri;
         LocalizedText ApplicationName;
         ApplicationType ApplicationType;
         std::string GatewayServerUri;
         std::string DiscoveryProfileUri;
         std::vector<std::string> DiscoveryUrls;
    };

    // ua:ExtensionObject
    struct RequestHeader 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId AuthenticationToken;
         DateTime Timestamp;
         uint32_t RequestHandle;
         uint32_t ReturnDiagnostics;
         std::string AuditEntryId;
         uint32_t TimeoutHint;
         ExtensionObject AdditionalHeader;

         RequestHeader();
    };

    // ua:ExtensionObject
    struct ResponseHeader 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DateTime Timestamp;
         uint32_t RequestHandle;
         StatusCode ServiceResult;
         DiagnosticInfo ServiceDiagnostics;
         std::vector<std::string> StringTable;
         ExtensionObject AdditionalHeader;

         ResponseHeader();
    };

    // ua:ExtensionObject
    struct ServiceFault 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ResponseHeader ResponseHeader;
    };

    struct FindServersParameters 
    {
         RequestHeader RequestHeader;
         std::string EndpointUrl;
         std::vector<std::string> LocaleIds;
         std::vector<std::string> ServerUris;
    };

    // ua:ExtensionObject
    struct FindServersRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         FindServersParameters Parameters;

         FindServersRequest();
    };

    struct FindServersData 
    {
         ResponseHeader ResponseHeader;
         std::vector<ApplicationDescription> Servers;
    };

    // ua:ExtensionObject
    struct FindServersResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         FindServersData Parameters;

         FindServersResponse();
    };

    // ua:ExtensionObject
    struct UserTokenPolicy 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string PolicyId;
         UserTokenType TokenType;
         std::string IssuedTokenType;
         std::string IssuerEndpointUrl;
         std::string SecurityPolicyUri;
    };

    // ua:ExtensionObject
    struct EndpointDescription 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string EndpointUrl;
         ApplicationDescription Server;
         ByteString ServerCertificate;
         MessageSecurityMode SecurityMode;
         std::string SecurityPolicyUri;
         std::vector<UserTokenPolicy> UserIdentityTokens;
         std::string TransportProfileUri;
         uint8_t SecurityLevel;
    };

    struct GetEndpointsParameters 
    {
         RequestHeader RequestHeader;
         std::string EndpointUrl;
         std::vector<std::string> LocaleIds;
         std::vector<std::string> ProfileUris;
    };

    // ua:ExtensionObject
    struct GetEndpointsRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         GetEndpointsParameters Parameters;

         GetEndpointsRequest();
    };

    // ua:ExtensionObject
    struct GetEndpointsResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ResponseHeader ResponseHeader;
         std::vector<EndpointDescription> Endpoints;

         GetEndpointsResponse();
    };

    // ua:ExtensionObject
    struct RegisteredServer 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string ServerUri;
         std::string ProductUri;
         std::vector<LocalizedText> ServerNames;
         ApplicationType ServerType;
         std::string GatewayServerUri;
         std::vector<std::string> DiscoveryUrls;
         std::string SemaphoreFilePath;
         bool IsOnline;
    };

    struct RegisterServerParameters 
    {
         RequestHeader RequestHeader;
         RegisteredServer Server;
    };

    // ua:ExtensionObject
    struct RegisterServerRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         RegisterServerParameters Parameters;

         RegisterServerRequest();
    };

    struct RegisterServerData 
    {
         ResponseHeader ResponseHeader;
    };

    // ua:ExtensionObject
    struct RegisterServerResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         RegisterServerData Parameters;

         RegisterServerResponse();
    };

    // ua:ExtensionObject
    struct ChannelSecurityToken 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t ChannelId;
         uint32_t TokenId;
         DateTime CreatedAt;
         uint32_t RevisedLifetime;
    };

    struct OpenSecureChannelParameters 
    {
         RequestHeader RequestHeader;
         uint32_t ClientProtocolVersion;
         SecurityTokenRequestType RequestType;
         MessageSecurityMode SecurityMode;
         ByteString ClientNonce;
         uint32_t RequestedLifetime;

         OpenSecureChannelParameters();
    };

    // ua:ExtensionObject
    struct OpenSecureChannelRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         OpenSecureChannelParameters Parameters;

         OpenSecureChannelRequest();
    };

    struct OpenSecureChannelData 
    {
         ResponseHeader ResponseHeader;
         uint32_t ServerProtocolVersion;
         ChannelSecurityToken SecurityToken;
         ByteString ServerNonce;
    };

    // ua:ExtensionObject
    struct OpenSecureChannelResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         OpenSecureChannelData Parameters;

         OpenSecureChannelResponse();
    };

    struct CloseSecureChannelParameters 
    {
         RequestHeader RequestHeader;
    };

    // ua:ExtensionObject
    struct CloseSecureChannelRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CloseSecureChannelParameters Parameters;

         CloseSecureChannelRequest();
    };

    struct CloseSecureChannelData 
    {
         ResponseHeader ResponseHeader;
    };

    // ua:ExtensionObject
    struct CloseSecureChannelResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CloseSecureChannelData Parameters;

         CloseSecureChannelResponse();
    };

    // ua:ExtensionObject
    struct SignedSoftwareCertificate 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ByteString CertificateData;
         ByteString Signature;
    };

    // ua:ExtensionObject
    struct SignatureData 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string Algorithm;
         ByteString Signature;
    };

    struct CreateSessionParameters 
    {
         RequestHeader RequestHeader;
         ApplicationDescription ClientDescription;
         std::string ServerUri;
         std::string EndpointUrl;
         std::string SessionName;
         ByteString ClientNonce;
         ByteString ClientCertificate;
         double RequestedSessionTimeout;
         uint32_t MaxResponseMessageSize;
    };

    // ua:ExtensionObject
    struct CreateSessionRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CreateSessionParameters Parameters;

         CreateSessionRequest();
    };

    struct CreateSessionData 
    {
         ResponseHeader ResponseHeader;
         NodeId SessionId;
         NodeId AuthenticationToken;
         double RevisedSessionTimeout;
         ByteString ServerNonce;
         ByteString ServerCertificate;
         std::vector<EndpointDescription> ServerEndpoints;
         std::vector<SignedSoftwareCertificate> ServerSoftwareCertificates;
         SignatureData ServerSignature;
         uint32_t MaxRequestMessageSize;
    };

    // ua:ExtensionObject
    struct CreateSessionResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CreateSessionData Parameters;

         CreateSessionResponse();
    };

    // ua:ExtensionObject
    struct UserIdentityToken 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string PolicyId;

         UserIdentityToken();
    };

    // tns:UserIdentityToken
    struct AnonymousIdentityToken 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string PolicyId;
         std::string PolicyId;
    };

    // tns:UserIdentityToken
    struct UserNameIdentityToken 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string PolicyId;
         std::string PolicyId;
         std::string UserName;
         ByteString Password;
         std::string EncryptionAlgorithm;
    };

    // tns:UserIdentityToken
    struct X509IdentityToken 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string PolicyId;
         std::string PolicyId;
         ByteString CertificateData;
    };

    // tns:UserIdentityToken
    struct IssuedIdentityToken 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string PolicyId;
         std::string PolicyId;
         ByteString TokenData;
         std::string EncryptionAlgorithm;
    };

    struct ActivateSessionParameters 
    {
         RequestHeader RequestHeader;
         SignatureData ClientSignature;
         std::vector<SignedSoftwareCertificate> ClientSoftwareCertificates;
         std::vector<std::string> LocaleIds;
         ExtensionObject UserIdentityToken;
         SignatureData UserTokenSignature;
    };

    // ua:ExtensionObject
    struct ActivateSessionRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ActivateSessionParameters Parameters;

         ActivateSessionRequest();
    };

    struct ActivateSessionData 
    {
         ResponseHeader ResponseHeader;
         ByteString ServerNonce;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    // ua:ExtensionObject
    struct ActivateSessionResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ActivateSessionData Parameters;

         ActivateSessionResponse();
    };

    struct CloseSessionParameters 
    {
         RequestHeader RequestHeader;
         bool DeleteSubscriptions;
    };

    // ua:ExtensionObject
    struct CloseSessionRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CloseSessionParameters Parameters;

         CloseSessionRequest();
    };

    struct CloseSessionData 
    {
         ResponseHeader ResponseHeader;
    };

    // ua:ExtensionObject
    struct CloseSessionResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CloseSessionData Parameters;

         CloseSessionResponse();
    };

    struct CancelParameters 
    {
         RequestHeader RequestHeader;
         uint32_t RequestHandle;
    };

    // ua:ExtensionObject
    struct CancelRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CancelParameters Parameters;

         CancelRequest();
    };

    struct CancelData 
    {
         ResponseHeader ResponseHeader;
         uint32_t CancelCount;
    };

    // ua:ExtensionObject
    struct CancelResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CancelData Parameters;

         CancelResponse();
    };

    // ua:ExtensionObject
    struct NodeAttributes 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
    };

    // tns:NodeAttributes
    struct ObjectAttributes 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         uint8_t EventNotifier;
    };

    // tns:NodeAttributes
    struct VariableAttributes 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         Variant Value;
         NodeId DataType;
         int32_t ValueRank;
         std::vector<uint32_t> ArrayDimensions;
         uint8_t AccessLevel;
         uint8_t UserAccessLevel;
         double MinimumSamplingInterval;
         bool Historizing;
    };

    // tns:NodeAttributes
    struct MethodAttributes 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         bool Executable;
         bool UserExecutable;
    };

    // tns:NodeAttributes
    struct ObjectTypeAttributes 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         bool IsAbstract;
    };

    // tns:NodeAttributes
    struct VariableTypeAttributes 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         Variant Value;
         NodeId DataType;
         int32_t ValueRank;
         std::vector<uint32_t> ArrayDimensions;
         bool IsAbstract;
    };

    // tns:NodeAttributes
    struct ReferenceTypeAttributes 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         bool IsAbstract;
         bool Symmetric;
         LocalizedText InverseName;
    };

    // tns:NodeAttributes
    struct DataTypeAttributes 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         bool IsAbstract;
    };

    // tns:NodeAttributes
    struct ViewAttributes 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         uint32_t SpecifiedAttributes;
         LocalizedText DisplayName;
         LocalizedText Description;
         uint32_t WriteMask;
         uint32_t UserWriteMask;
         bool ContainsNoLoops;
         uint8_t EventNotifier;
    };

    // ua:ExtensionObject
    struct AddNodesItem 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ExpandedNodeId ParentNodeId;
         NodeId ReferenceTypeId;
         ExpandedNodeId RequestedNewNodeId;
         QualifiedName BrowseName;
         NodeClass NodeClass;
         ExtensionObject NodeAttributes;
         ExpandedNodeId TypeDefinition;
    };

    // ua:ExtensionObject
    struct AddNodesResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         NodeId AddedNodeId;
    };

    struct AddNodesParameters 
    {
         RequestHeader RequestHeader;
         std::vector<AddNodesItem> NodesToAdd;
    };

    // ua:ExtensionObject
    struct AddNodesRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         AddNodesParameters Parameters;

         AddNodesRequest();
    };

    struct AddNodesData 
    {
         ResponseHeader ResponseHeader;
         std::vector<AddNodesResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    // ua:ExtensionObject
    struct AddNodesResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         AddNodesData Parameters;

         AddNodesResponse();
    };

    // ua:ExtensionObject
    struct AddReferencesItem 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId SourceNodeId;
         NodeId ReferenceTypeId;
         bool IsForward;
         std::string TargetServerUri;
         ExpandedNodeId TargetNodeId;
         NodeClass TargetNodeClass;
    };

    struct AddReferencesParameters 
    {
         RequestHeader RequestHeader;
         std::vector<AddReferencesItem> ReferencesToAdd;
    };

    // ua:ExtensionObject
    struct AddReferencesRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         AddReferencesParameters Parameters;

         AddReferencesRequest();
    };

    struct AddReferencesData 
    {
         ResponseHeader ResponseHeader;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    // ua:ExtensionObject
    struct AddReferencesResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         AddReferencesData Parameters;

         AddReferencesResponse();
    };

    // ua:ExtensionObject
    struct DeleteNodesItem 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         bool DeleteTargetReferences;
    };

    struct DeleteNodesParameters 
    {
         RequestHeader RequestHeader;
         std::vector<DeleteNodesItem> NodesToDelete;
    };

    // ua:ExtensionObject
    struct DeleteNodesRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DeleteNodesParameters Parameters;

         DeleteNodesRequest();
    };

    struct DeleteNodesData 
    {
         ResponseHeader ResponseHeader;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    // ua:ExtensionObject
    struct DeleteNodesResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DeleteNodesData Parameters;

         DeleteNodesResponse();
    };

    // ua:ExtensionObject
    struct DeleteReferencesItem 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId SourceNodeId;
         NodeId ReferenceTypeId;
         bool IsForward;
         ExpandedNodeId TargetNodeId;
         bool DeleteBidirectional;
    };

    struct DeleteReferencesParameters 
    {
         RequestHeader RequestHeader;
         std::vector<DeleteReferencesItem> ReferencesToDelete;
    };

    // ua:ExtensionObject
    struct DeleteReferencesRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DeleteReferencesParameters Parameters;

         DeleteReferencesRequest();
    };

    struct DeleteReferencesData 
    {
         ResponseHeader ResponseHeader;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    // ua:ExtensionObject
    struct DeleteReferencesResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DeleteReferencesData Parameters;

         DeleteReferencesResponse();
    };

    // ua:ExtensionObject
    struct ViewDescription 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId ViewId;
         DateTime Timestamp;
         uint32_t ViewVersion;
    };

    // ua:ExtensionObject
    struct BrowseDescription 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         BrowseDirection BrowseDirection;
         NodeId ReferenceTypeId;
         bool IncludeSubtypes;
         uint32_t NodeClassMask;
         uint32_t ResultMask;
    };

    // ua:ExtensionObject
    struct ReferenceDescription 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId ReferenceTypeId;
         bool IsForward;
         ExpandedNodeId NodeId;
         QualifiedName BrowseName;
         LocalizedText DisplayName;
         NodeClass NodeClass;
         ExpandedNodeId TypeDefinition;
    };

    // ua:ExtensionObject
    struct BrowseResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         ByteString ContinuationPoint;
         std::vector<ReferenceDescription> References;
    };

    struct BrowseParameters 
    {
         RequestHeader RequestHeader;
         ViewDescription View;
         uint32_t RequestedMaxReferencesPerNode;
         std::vector<BrowseDescription> NodesToBrowse;
    };

    // ua:ExtensionObject
    struct BrowseRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         BrowseParameters Parameters;

         BrowseRequest();
    };

    struct BrowseData 
    {
         ResponseHeader ResponseHeader;
         std::vector<BrowseResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    // ua:ExtensionObject
    struct BrowseResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         BrowseData Parameters;

         BrowseResponse();
    };

    struct BrowseNextParameters 
    {
         RequestHeader RequestHeader;
         bool ReleaseContinuationPoints;
         std::vector<ByteString> ContinuationPoints;
    };

    // ua:ExtensionObject
    struct BrowseNextRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         BrowseNextParameters Parameters;

         BrowseNextRequest();
    };

    struct BrowseNextData 
    {
         ResponseHeader ResponseHeader;
         std::vector<BrowseResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    // ua:ExtensionObject
    struct BrowseNextResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         BrowseNextData Parameters;

         BrowseNextResponse();
    };

    // ua:ExtensionObject
    struct RelativePathElement 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId ReferenceTypeId;
         bool IsInverse;
         bool IncludeSubtypes;
         QualifiedName TargetName;

         RelativePathElement();
    };

    // ua:ExtensionObject
    struct RelativePath 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<RelativePathElement> Elements;
    };

    // ua:ExtensionObject
    struct BrowsePath 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId StartingNode;
         RelativePath RelativePath;
    };

    // ua:ExtensionObject
    struct BrowsePathTarget 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ExpandedNodeId TargetId;
         uint32_t RemainingPathIndex;
    };

    // ua:ExtensionObject
    struct BrowsePathResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         std::vector<BrowsePathTarget> Targets;
    };

    struct TranslateBrowsePathsToNodeIdsParameters 
    {
         RequestHeader RequestHeader;
         std::vector<BrowsePath> BrowsePaths;
    };

    // ua:ExtensionObject
    struct TranslateBrowsePathsToNodeIdsRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         TranslateBrowsePathsToNodeIdsParameters Parameters;

         TranslateBrowsePathsToNodeIdsRequest();
    };

    struct TranslateBrowsePathsToNodeIdsData 
    {
         ResponseHeader ResponseHeader;
         std::vector<BrowsePathResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    // ua:ExtensionObject
    struct TranslateBrowsePathsToNodeIdsResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         TranslateBrowsePathsToNodeIdsData Parameters;

         TranslateBrowsePathsToNodeIdsResponse();
    };

    struct RegisterNodesParameters 
    {
         RequestHeader RequestHeader;
         std::vector<NodeId> NodesToRegister;
    };

    // ua:ExtensionObject
    struct RegisterNodesRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         RegisterNodesParameters Parameters;

         RegisterNodesRequest();
    };

    struct RegisterNodesData 
    {
         ResponseHeader ResponseHeader;
         std::vector<NodeId> RegisteredNodeIds;
    };

    // ua:ExtensionObject
    struct RegisterNodesResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         RegisterNodesData Parameters;

         RegisterNodesResponse();
    };

    struct UnregisterNodesParameters 
    {
         RequestHeader RequestHeader;
         std::vector<NodeId> NodesToUnregister;
    };

    // ua:ExtensionObject
    struct UnregisterNodesRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         UnregisterNodesParameters Parameters;

         UnregisterNodesRequest();
    };

    struct UnregisterNodesData 
    {
         ResponseHeader ResponseHeader;
    };

    // ua:ExtensionObject
    struct UnregisterNodesResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         UnregisterNodesData Parameters;

         UnregisterNodesResponse();
    };

    struct EndpointConfiguration 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         int32_t OperationTimeout;
         bool UseBinaryEncoding;
         int32_t MaxStringLength;
         int32_t MaxByteStringLength;
         int32_t MaxArrayLength;
         int32_t MaxMessageSize;
         int32_t MaxBufferSize;
         int32_t ChannelLifetime;
         int32_t SecurityTokenLifetime;
    };

    struct SupportedProfile 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string OrganizationUri;
         std::string ProfileId;
         std::string ComplianceTool;
         DateTime ComplianceDate;
         ComplianceLevel ComplianceLevel;
         std::vector<std::string> UnsupportedUnitIds;
    };

    struct SoftwareCertificate 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string ProductName;
         std::string ProductUri;
         std::string VendorName;
         ByteString VendorProductCertificate;
         std::string SoftwareVersion;
         std::string BuildNumber;
         DateTime BuildDate;
         std::string IssuedBy;
         DateTime IssueDate;
         std::vector<SupportedProfile> SupportedProfiles;
    };

    struct QueryDataDescription 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         RelativePath RelativePath;
         uint32_t AttributeId;
         std::string IndexRange;
    };

    struct NodeTypeDescription 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ExpandedNodeId TypeDefinitionNode;
         bool IncludeSubTypes;
         std::vector<QueryDataDescription> DataToReturn;
    };

    struct QueryDataSet 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ExpandedNodeId NodeId;
         ExpandedNodeId TypeDefinitionNode;
         std::vector<Variant> Values;
    };

    struct NodeReference 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         NodeId ReferenceTypeId;
         bool IsForward;
         std::vector<NodeId> ReferencedNodeIds;
    };

    struct ContentFilterElement 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         FilterOperator FilterOperator;
         std::vector<ExtensionObject> FilterOperands;
    };

    struct ContentFilter 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<ContentFilterElement> Elements;
    };

    struct FilterOperand 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
    };

    struct ElementOperand 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t Index;
    };

    struct LiteralOperand 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         Variant Value;
    };

    struct AttributeOperand 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         std::string Alias;
         RelativePath BrowsePath;
         uint32_t AttributeId;
         std::string IndexRange;
    };

    struct SimpleAttributeOperand 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId TypeDefinitionId;
         std::vector<QualifiedName> BrowsePath;
         uint32_t AttributeId;
         std::string IndexRange;
    };

    struct ContentFilterElementResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         std::vector<StatusCode> OperandStatusCodes;
         std::vector<DiagnosticInfo> OperandDiagnosticInfos;
    };

    struct ContentFilterResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<ContentFilterElementResult> ElementResults;
         std::vector<DiagnosticInfo> ElementDiagnosticInfos;
    };

    struct ParsingResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         std::vector<StatusCode> DataStatusCodes;
         std::vector<DiagnosticInfo> DataDiagnosticInfos;
    };

    struct QueryFirstParameters 
    {
         RequestHeader RequestHeader;
         ViewDescription View;
         std::vector<NodeTypeDescription> NodeTypes;
         ContentFilter Filter;
         uint32_t MaxDataSetsToReturn;
         uint32_t MaxReferencesToReturn;
    };

    struct QueryFirstRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         QueryFirstParameters Parameters;

         QueryFirstRequest();
    };

    struct QueryFirstData 
    {
         ResponseHeader ResponseHeader;
         std::vector<QueryDataSet> QueryDataSets;
         ByteString ContinuationPoint;
         std::vector<ParsingResult> ParsingResults;
         std::vector<DiagnosticInfo> DiagnosticInfos;
         ContentFilterResult FilterResult;
    };

    struct QueryFirstResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         QueryFirstData Parameters;

         QueryFirstResponse();
    };

    struct QueryNextParameters 
    {
         RequestHeader RequestHeader;
         bool ReleaseContinuationPoint;
         ByteString ContinuationPoint;
    };

    struct QueryNextRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         QueryNextParameters Parameters;

         QueryNextRequest();
    };

    struct QueryNextData 
    {
         ResponseHeader ResponseHeader;
         std::vector<QueryDataSet> QueryDataSets;
         ByteString RevisedContinuationPoint;
    };

    struct QueryNextResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         QueryNextData Parameters;

         QueryNextResponse();
    };

    struct ReadValueId 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         uint32_t AttributeId;
         std::string IndexRange;
         QualifiedName DataEncoding;

         ReadValueId();
    };

    struct ReadParameters 
    {
         RequestHeader RequestHeader;
         double MaxAge;
         TimestampsToReturn TimestampsToReturn;
         std::vector<ReadValueId> NodesToRead;
    };

    struct ReadRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ReadParameters Parameters;

         ReadRequest();
    };

    struct ReadData 
    {
         ResponseHeader ResponseHeader;
         std::vector<DataValue> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct ReadResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ReadData Parameters;

         ReadResponse();
    };

    struct HistoryReadValueId 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         std::string IndexRange;
         QualifiedName DataEncoding;
         ByteString ContinuationPoint;
    };

    struct HistoryReadResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         ByteString ContinuationPoint;
         ExtensionObject HistoryData;
    };

    struct HistoryReadDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
    };

    struct ReadEventDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t NumValuesPerNode;
         DateTime StartTime;
         DateTime EndTime;
         EventFilter Filter;
    };

    struct ReadRawModifiedDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         bool IsReadModified;
         DateTime StartTime;
         DateTime EndTime;
         uint32_t NumValuesPerNode;
         bool ReturnBounds;
    };

    struct ReadProcessedDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DateTime StartTime;
         DateTime EndTime;
         double ProcessingInterval;
         std::vector<NodeId> AggregateType;
         AggregateConfiguration AggregateConfiguration;
    };

    struct ReadAtTimeDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<DateTime> ReqTimes;
         bool UseSimpleBounds;
    };

    struct HistoryData 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<DataValue> DataValues;
    };

    struct ModificationInfo 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DateTime ModificationTime;
         HistoryUpdateType UpdateType;
         std::string UserName;
    };

    struct HistoryModifiedData 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<DataValue> DataValues;
         std::vector<DataValue> DataValues;
         std::vector<ModificationInfo> ModificationInfos;
    };

    struct HistoryEvent 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<HistoryEventFieldList> Events;
    };

    struct HistoryReadParameters 
    {
         RequestHeader RequestHeader;
         ExtensionObject HistoryReadDetails;
         TimestampsToReturn TimestampsToReturn;
         bool ReleaseContinuationPoints;
         std::vector<HistoryReadValueId> NodesToRead;
    };

    struct HistoryReadRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         HistoryReadParameters Parameters;

         HistoryReadRequest();
    };

    struct HistoryReadData 
    {
         ResponseHeader ResponseHeader;
         std::vector<HistoryReadResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct HistoryReadResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         HistoryReadData Parameters;

         HistoryReadResponse();
    };

    struct WriteValue 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         uint32_t AttributeId;
         std::string IndexRange;
         DataValue Value;
    };

    struct WriteParameters 
    {
         RequestHeader RequestHeader;
         std::vector<WriteValue> NodesToWrite;
    };

    struct WriteRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         WriteParameters Parameters;

         WriteRequest();
    };

    struct WriteData 
    {
         ResponseHeader ResponseHeader;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct WriteResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         WriteData Parameters;

         WriteResponse();
    };

    struct HistoryUpdateDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
    };

    struct UpdateDataDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         NodeId NodeId;
         PerformUpdateType PerformInsertReplace;
         std::vector<DataValue> UpdateValues;
    };

    struct UpdateStructureDataDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         NodeId NodeId;
         PerformUpdateType PerformInsertReplace;
         std::vector<DataValue> UpdateValues;
    };

    struct UpdateEventDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         NodeId NodeId;
         PerformUpdateType PerformInsertReplace;
         EventFilter Filter;
         std::vector<HistoryEventFieldList> EventData;
    };

    struct DeleteRawModifiedDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         NodeId NodeId;
         bool IsDeleteModified;
         DateTime StartTime;
         DateTime EndTime;
    };

    struct DeleteAtTimeDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         NodeId NodeId;
         std::vector<DateTime> ReqTimes;
    };

    struct DeleteEventDetails 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId NodeId;
         NodeId NodeId;
         std::vector<ByteString> EventIds;
    };

    struct HistoryUpdateResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         std::vector<StatusCode> OperationResults;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct HistoryUpdateEventResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         EventFilterResult EventFilterResult;
    };

    struct HistoryUpdateParameters 
    {
         RequestHeader RequestHeader;
         std::vector<ExtensionObject> HistoryUpdateDetails;
    };

    struct HistoryUpdateRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         HistoryUpdateParameters Parameters;

         HistoryUpdateRequest();
    };

    struct HistoryUpdateData 
    {
         ResponseHeader ResponseHeader;
         std::vector<HistoryUpdateResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct HistoryUpdateResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         HistoryUpdateData Parameters;

         HistoryUpdateResponse();
    };

    struct CallMethodParameters 
    {
         NodeId ObjectId;
         NodeId MethodId;
         std::vector<Variant> InputArguments;
    };

    struct CallMethodRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CallMethodParameters Parameters;

         CallMethodRequest();
    };

    struct CallMethodResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         std::vector<StatusCode> InputArgumentResults;
         std::vector<DiagnosticInfo> InputArgumentDiagnosticInfos;
         std::vector<Variant> OutputArguments;
    };

    struct CallParameters 
    {
         RequestHeader RequestHeader;
         std::vector<CallMethodRequest> MethodsToCall;
    };

    struct CallRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CallParameters Parameters;

         CallRequest();
    };

    struct CallData 
    {
         ResponseHeader ResponseHeader;
         std::vector<CallMethodResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct CallResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CallData Parameters;

         CallResponse();
    };

    struct MonitoringFilter 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
    };

    struct DataChangeFilter 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DataChangeTrigger Trigger;
         uint32_t DeadbandType;
         double DeadbandValue;
    };

    struct EventFilter 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<SimpleAttributeOperand> SelectClauses;
         ContentFilter WhereClause;
    };

    struct AggregateConfiguration 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         bool UseServerCapabilitiesDefaults;
         bool TreatUncertainAsBad;
         uint8_t PercentDataBad;
         uint8_t PercentDataGood;
         bool UseSlopedExtrapolation;
    };

    struct AggregateFilter 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DateTime StartTime;
         NodeId AggregateType;
         double ProcessingInterval;
         AggregateConfiguration AggregateConfiguration;
    };

    struct MonitoringFilterResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
    };

    struct EventFilterResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<StatusCode> SelectClauseResults;
         std::vector<DiagnosticInfo> SelectClauseDiagnosticInfos;
         ContentFilterResult WhereClauseResult;
    };

    struct AggregateFilterResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DateTime RevisedStartTime;
         double RevisedProcessingInterval;
         AggregateConfiguration RevisedAggregateConfiguration;
    };

    struct MonitoringParameters 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t ClientHandle;
         double SamplingInterval;
         ExtensionObject Filter;
         uint32_t QueueSize;
         bool DiscardOldest;
    };

    struct MonitoredItemCreateParameters 
    {
         ReadValueId ItemToMonitor;
         MonitoringMode MonitoringMode;
         MonitoringParameters RequestedParameters;
    };

    struct MonitoredItemCreateRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         MonitoredItemCreateParameters Parameters;

         MonitoredItemCreateRequest();
    };

    struct MonitoredItemCreateResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         uint32_t MonitoredItemId;
         double RevisedSamplingInterval;
         uint32_t RevisedQueueSize;
         ExtensionObject FilterResult;
    };

    struct CreateMonitoredItemsParameters 
    {
         RequestHeader RequestHeader;
         uint32_t SubscriptionId;
         TimestampsToReturn TimestampsToReturn;
         std::vector<MonitoredItemCreateRequest> ItemsToCreate;
    };

    struct CreateMonitoredItemsRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CreateMonitoredItemsParameters Parameters;

         CreateMonitoredItemsRequest();
    };

    struct CreateMonitoredItemsData 
    {
         ResponseHeader ResponseHeader;
         std::vector<MonitoredItemCreateResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct CreateMonitoredItemsResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CreateMonitoredItemsData Parameters;

         CreateMonitoredItemsResponse();
    };

    struct MonitoredItemModifyParameters 
    {
         uint32_t MonitoredItemId;
         MonitoringParameters RequestedParameters;
    };

    struct MonitoredItemModifyRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         MonitoredItemModifyParameters Parameters;

         MonitoredItemModifyRequest();
    };

    struct MonitoredItemModifyResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         double RevisedSamplingInterval;
         uint32_t RevisedQueueSize;
         ExtensionObject FilterResult;
    };

    struct ModifyMonitoredItemsParameters 
    {
         RequestHeader RequestHeader;
         uint32_t SubscriptionId;
         TimestampsToReturn TimestampsToReturn;
         std::vector<MonitoredItemModifyRequest> ItemsToModify;
    };

    struct ModifyMonitoredItemsRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ModifyMonitoredItemsParameters Parameters;

         ModifyMonitoredItemsRequest();
    };

    struct ModifyMonitoredItemsData 
    {
         ResponseHeader ResponseHeader;
         std::vector<MonitoredItemModifyResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct ModifyMonitoredItemsResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ModifyMonitoredItemsData Parameters;

         ModifyMonitoredItemsResponse();
    };

    struct SetMonitoringModeParameters 
    {
         RequestHeader RequestHeader;
         uint32_t SubscriptionId;
         MonitoringMode MonitoringMode;
         std::vector<uint32_t> MonitoredItemIds;
    };

    struct SetMonitoringModeRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         SetMonitoringModeParameters Parameters;

         SetMonitoringModeRequest();
    };

    struct SetMonitoringModeData 
    {
         ResponseHeader ResponseHeader;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct SetMonitoringModeResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         SetMonitoringModeData Parameters;

         SetMonitoringModeResponse();
    };

    struct SetTriggeringParameters 
    {
         RequestHeader RequestHeader;
         uint32_t SubscriptionId;
         uint32_t TriggeringItemId;
         std::vector<uint32_t> LinksToAdd;
         std::vector<uint32_t> LinksToRemove;
    };

    struct SetTriggeringRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         SetTriggeringParameters Parameters;

         SetTriggeringRequest();
    };

    struct SetTriggeringData 
    {
         ResponseHeader ResponseHeader;
         std::vector<StatusCode> AddResults;
         std::vector<DiagnosticInfo> AddDiagnosticInfos;
         std::vector<StatusCode> RemoveResults;
         std::vector<DiagnosticInfo> RemoveDiagnosticInfos;
    };

    struct SetTriggeringResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         SetTriggeringData Parameters;

         SetTriggeringResponse();
    };

    struct DeleteMonitoredItemsParameters 
    {
         RequestHeader RequestHeader;
         uint32_t SubscriptionId;
         std::vector<uint32_t> MonitoredItemIds;
    };

    struct DeleteMonitoredItemsRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DeleteMonitoredItemsParameters Parameters;

         DeleteMonitoredItemsRequest();
    };

    struct DeleteMonitoredItemsData 
    {
         ResponseHeader ResponseHeader;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct DeleteMonitoredItemsResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DeleteMonitoredItemsData Parameters;

         DeleteMonitoredItemsResponse();
    };

    struct CreateSubscriptionParameters 
    {
         RequestHeader RequestHeader;
         double RequestedPublishingInterval;
         uint32_t RequestedLifetimeCount;
         uint32_t RequestedMaxKeepAliveCount;
         uint32_t MaxNotificationsPerPublish;
         bool PublishingEnabled;
         uint8_t Priority;
    };

    struct CreateSubscriptionRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CreateSubscriptionParameters Parameters;

         CreateSubscriptionRequest();
    };

    struct CreateSubscriptionData 
    {
         ResponseHeader ResponseHeader;
         uint32_t SubscriptionId;
         double RevisedPublishingInterval;
         uint32_t RevisedLifetimeCount;
         uint32_t RevisedMaxKeepAliveCount;
    };

    struct CreateSubscriptionResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         CreateSubscriptionData Parameters;

         CreateSubscriptionResponse();
    };

    struct ModifySubscriptionParameters 
    {
         RequestHeader RequestHeader;
         uint32_t SubscriptionId;
         double RequestedPublishingInterval;
         uint32_t RequestedLifetimeCount;
         uint32_t RequestedMaxKeepAliveCount;
         uint32_t MaxNotificationsPerPublish;
         uint8_t Priority;
    };

    struct ModifySubscriptionRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ModifySubscriptionParameters Parameters;

         ModifySubscriptionRequest();
    };

    struct ModifySubscriptionData 
    {
         ResponseHeader ResponseHeader;
         double RevisedPublishingInterval;
         uint32_t RevisedLifetimeCount;
         uint32_t RevisedMaxKeepAliveCount;
    };

    struct ModifySubscriptionResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ModifySubscriptionData Parameters;

         ModifySubscriptionResponse();
    };

    struct SetPublishingModeParameters 
    {
         RequestHeader RequestHeader;
         bool PublishingEnabled;
         std::vector<uint32_t> SubscriptionIds;
    };

    struct SetPublishingModeRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         SetPublishingModeParameters Parameters;

         SetPublishingModeRequest();
    };

    struct SetPublishingModeData 
    {
         ResponseHeader ResponseHeader;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct SetPublishingModeResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         SetPublishingModeData Parameters;

         SetPublishingModeResponse();
    };

    struct NotificationMessage 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SequenceNumber;
         DateTime PublishTime;
         std::vector<ExtensionObject> NotificationData;
    };

    struct NotificationData 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
    };

    struct DataChangeNotification 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<MonitoredItemNotification> MonitoredItems;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct MonitoredItemNotification 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t ClientHandle;
         DataValue Value;
    };

    struct EventNotificationList 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<EventFieldList> Events;
    };

    struct EventFieldList 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t ClientHandle;
         std::vector<Variant> EventFields;
    };

    struct HistoryEventFieldList 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<Variant> EventFields;
    };

    struct StatusChangeNotification 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode Status;
         DiagnosticInfo DiagnosticInfo;
    };

    struct SubscriptionAcknowledgement 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t SubscriptionId;
         uint32_t SequenceNumber;
    };

    struct PublishParameters 
    {
         RequestHeader RequestHeader;
         std::vector<SubscriptionAcknowledgement> SubscriptionAcknowledgements;
    };

    struct PublishRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         PublishParameters Parameters;

         PublishRequest();
    };

    struct PublishData 
    {
         ResponseHeader ResponseHeader;
         uint32_t SubscriptionId;
         std::vector<uint32_t> AvailableSequenceNumbers;
         bool MoreNotifications;
         NotificationMessage NotificationMessage;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct PublishResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         PublishData Parameters;

         PublishResponse();
    };

    struct RepublishParameters 
    {
         RequestHeader RequestHeader;
         uint32_t SubscriptionId;
         uint32_t RetransmitSequenceNumber;
    };

    struct RepublishRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         RepublishParameters Parameters;

         RepublishRequest();
    };

    struct RepublishData 
    {
         ResponseHeader ResponseHeader;
         NotificationMessage NotificationMessage;
    };

    struct RepublishResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         RepublishData Parameters;

         RepublishResponse();
    };

    struct TransferResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         std::vector<uint32_t> AvailableSequenceNumbers;
    };

    struct TransferSubscriptionsParameters 
    {
         RequestHeader RequestHeader;
         std::vector<uint32_t> SubscriptionIds;
         bool SendInitialValues;
    };

    struct TransferSubscriptionsRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         TransferSubscriptionsParameters Parameters;

         TransferSubscriptionsRequest();
    };

    struct TransferSubscriptionsData 
    {
         ResponseHeader ResponseHeader;
         std::vector<TransferResult> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct TransferSubscriptionsResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         TransferSubscriptionsData Parameters;

         TransferSubscriptionsResponse();
    };

    struct DeleteSubscriptionsParameters 
    {
         RequestHeader RequestHeader;
         std::vector<uint32_t> SubscriptionIds;
    };

    struct DeleteSubscriptionsRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DeleteSubscriptionsParameters Parameters;

         DeleteSubscriptionsRequest();
    };

    struct DeleteSubscriptionsData 
    {
         ResponseHeader ResponseHeader;
         std::vector<StatusCode> Results;
         std::vector<DiagnosticInfo> DiagnosticInfos;
    };

    struct DeleteSubscriptionsResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DeleteSubscriptionsData Parameters;

         DeleteSubscriptionsResponse();
    };

    // ua:ExtensionObject
    struct ScalarTestType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         bool Boolean;
         char SByte;
         uint8_t Byte;
         int16_t Int16;
         uint16_t UInt16;
         int32_t Int32;
         uint32_t UInt32;
         int64_t Int64;
         uint64_t UInt64;
         float Float;
         double Double;
         std::string String;
         DateTime DateTime;
         opc:Guid Guid;
         ByteString ByteString;
         XmlElement XmlElement;
         NodeId NodeId;
         ExpandedNodeId ExpandedNodeId;
         StatusCode StatusCode;
         DiagnosticInfo DiagnosticInfo;
         QualifiedName QualifiedName;
         LocalizedText LocalizedText;
         ExtensionObject ExtensionObject;
         DataValue DataValue;
         EnumeratedTestType EnumeratedValue;
    };

    // ua:ExtensionObject
    struct ArrayTestType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<bool> Booleans;
         std::vector<char> SBytes;
         std::vector<int16_t> Int16s;
         std::vector<uint16_t> UInt16s;
         std::vector<int32_t> Int32s;
         std::vector<uint32_t> UInt32s;
         std::vector<int64_t> Int64s;
         std::vector<uint64_t> UInt64s;
         std::vector<float> Floats;
         std::vector<double> Doubles;
         std::vector<std::string> Strings;
         std::vector<DateTime> DateTimes;
         std::vector<opc:Guid> Guids;
         std::vector<ByteString> ByteStrings;
         std::vector<XmlElement> XmlElements;
         std::vector<NodeId> NodeIds;
         std::vector<ExpandedNodeId> ExpandedNodeIds;
         std::vector<StatusCode> StatusCodes;
         std::vector<DiagnosticInfo> DiagnosticInfos;
         std::vector<QualifiedName> QualifiedNames;
         std::vector<LocalizedText> LocalizedTexts;
         std::vector<ExtensionObject> ExtensionObjects;
         std::vector<DataValue> DataValues;
         std::vector<Variant> Variants;
         std::vector<EnumeratedTestType> EnumeratedValues;
    };

    struct CompositeTestType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         ScalarTestType Field1;
         ArrayTestType Field2;
    };

    struct TestStackParameters 
    {
         RequestHeader RequestHeader;
         uint32_t TestId;
         int32_t Iteration;
         Variant Input;
    };

    struct TestStackRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         TestStackParameters Parameters;

         TestStackRequest();
    };

    struct TestStackData 
    {
         ResponseHeader ResponseHeader;
         Variant Output;
    };

    struct TestStackResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         TestStackData Parameters;

         TestStackResponse();
    };

    struct TestStackExParameters 
    {
         RequestHeader RequestHeader;
         uint32_t TestId;
         int32_t Iteration;
         CompositeTestType Input;
    };

    struct TestStackExRequest 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         TestStackExParameters Parameters;

         TestStackExRequest();
    };

    struct TestStackExData 
    {
         ResponseHeader ResponseHeader;
         CompositeTestType Output;
    };

    struct TestStackExResponse 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         TestStackExData Parameters;

         TestStackExResponse();
    };

    struct BuildInfo 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string ProductUri;
         std::string ManufacturerName;
         std::string ProductName;
         std::string SoftwareVersion;
         std::string BuildNumber;
         DateTime BuildDate;
    };

    struct RedundantServerDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string ServerId;
         uint8_t ServiceLevel;
         ServerState ServerState;
    };

    struct EndpointUrlListDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::vector<std::string> EndpointUrlList;
    };

    struct NetworkGroupDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string ServerUri;
         std::vector<EndpointUrlListDataType> NetworkPaths;
    };

    struct SamplingIntervalDiagnosticsDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         double SamplingInterval;
         uint32_t MonitoredItemCount;
         uint32_t MaxMonitoredItemCount;
         uint32_t DisabledMonitoredItemCount;
    };

    struct ServerDiagnosticsSummaryDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t ServerViewCount;
         uint32_t CurrentSessionCount;
         uint32_t CumulatedSessionCount;
         uint32_t SecurityRejectedSessionCount;
         uint32_t RejectedSessionCount;
         uint32_t SessionTimeoutCount;
         uint32_t SessionAbortCount;
         uint32_t CurrentSubscriptionCount;
         uint32_t CumulatedSubscriptionCount;
         uint32_t PublishingIntervalCount;
         uint32_t SecurityRejectedRequestsCount;
         uint32_t RejectedRequestsCount;
    };

    struct ServerStatusDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         DateTime StartTime;
         DateTime CurrentTime;
         ServerState State;
         BuildInfo BuildInfo;
         uint32_t SecondsTillShutdown;
         LocalizedText ShutdownReason;
    };

    struct SessionDiagnosticsDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId SessionId;
         std::string SessionName;
         ApplicationDescription ClientDescription;
         std::string ServerUri;
         std::string EndpointUrl;
         std::vector<std::string> LocaleIds;
         double ActualSessionTimeout;
         uint32_t MaxResponseMessageSize;
         DateTime ClientConnectionTime;
         DateTime ClientLastContactTime;
         uint32_t CurrentSubscriptionsCount;
         uint32_t CurrentMonitoredItemsCount;
         uint32_t CurrentPublishRequestsInQueue;
         ServiceCounterDataType TotalRequestCount;
         uint32_t UnauthorizedRequestCount;
         ServiceCounterDataType ReadCount;
         ServiceCounterDataType HistoryReadCount;
         ServiceCounterDataType WriteCount;
         ServiceCounterDataType HistoryUpdateCount;
         ServiceCounterDataType CallCount;
         ServiceCounterDataType CreateMonitoredItemsCount;
         ServiceCounterDataType ModifyMonitoredItemsCount;
         ServiceCounterDataType SetMonitoringModeCount;
         ServiceCounterDataType SetTriggeringCount;
         ServiceCounterDataType DeleteMonitoredItemsCount;
         ServiceCounterDataType CreateSubscriptionCount;
         ServiceCounterDataType ModifySubscriptionCount;
         ServiceCounterDataType SetPublishingModeCount;
         ServiceCounterDataType PublishCount;
         ServiceCounterDataType RepublishCount;
         ServiceCounterDataType TransferSubscriptionsCount;
         ServiceCounterDataType DeleteSubscriptionsCount;
         ServiceCounterDataType AddNodesCount;
         ServiceCounterDataType AddReferencesCount;
         ServiceCounterDataType DeleteNodesCount;
         ServiceCounterDataType DeleteReferencesCount;
         ServiceCounterDataType BrowseCount;
         ServiceCounterDataType BrowseNextCount;
         ServiceCounterDataType TranslateBrowsePathsToNodeIdsCount;
         ServiceCounterDataType QueryFirstCount;
         ServiceCounterDataType QueryNextCount;
         ServiceCounterDataType RegisterNodesCount;
         ServiceCounterDataType UnregisterNodesCount;
    };

    struct SessionSecurityDiagnosticsDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId SessionId;
         std::string ClientUserIdOfSession;
         std::vector<std::string> ClientUserIdHistory;
         std::string AuthenticationMechanism;
         std::string Encoding;
         std::string TransportProtocol;
         MessageSecurityMode SecurityMode;
         std::string SecurityPolicyUri;
         ByteString ClientCertificate;
    };

    struct ServiceCounterDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         uint32_t TotalCount;
         uint32_t ErrorCount;
    };

    struct StatusResult 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         StatusCode StatusCode;
         DiagnosticInfo DiagnosticInfo;
    };

    struct SubscriptionDiagnosticsDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId SessionId;
         uint32_t SubscriptionId;
         uint8_t Priority;
         double PublishingInterval;
         uint32_t MaxKeepAliveCount;
         uint32_t MaxLifetimeCount;
         uint32_t MaxNotificationsPerPublish;
         bool PublishingEnabled;
         uint32_t ModifyCount;
         uint32_t EnableCount;
         uint32_t DisableCount;
         uint32_t RepublishRequestCount;
         uint32_t RepublishMessageRequestCount;
         uint32_t RepublishMessageCount;
         uint32_t TransferRequestCount;
         uint32_t TransferredToAltClientCount;
         uint32_t TransferredToSameClientCount;
         uint32_t PublishRequestCount;
         uint32_t DataChangeNotificationsCount;
         uint32_t EventNotificationsCount;
         uint32_t NotificationsCount;
         uint32_t LatePublishRequestCount;
         uint32_t CurrentKeepAliveCount;
         uint32_t CurrentLifetimeCount;
         uint32_t UnacknowledgedMessageCount;
         uint32_t DiscardedMessageCount;
         uint32_t MonitoredItemCount;
         uint32_t DisabledMonitoredItemCount;
         uint32_t MonitoringQueueOverflowCount;
         uint32_t NextSequenceNumber;
         uint32_t EventQueueOverFlowCount;
    };

    struct ModelChangeStructureDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId Affected;
         NodeId AffectedType;
         uint8_t Verb;
    };

    struct SemanticChangeStructureDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId Affected;
         NodeId AffectedType;
    };

    struct Range 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         double Low;
         double High;
    };

    struct EUInformation 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string NamespaceUri;
         int32_t UnitId;
         LocalizedText DisplayName;
         LocalizedText Description;
    };

    struct ComplexNumberType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         float Real;
         float Imaginary;
    };

    struct DoubleComplexNumberType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         double Real;
         double Imaginary;
    };

    struct AxisInformation 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         EUInformation EngineeringUnits;
         Range EURange;
         LocalizedText Title;
         AxisScaleEnumeration AxisScaleType;
         std::vector<double> AxisSteps;
    };

    struct XVType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         double X;
         float Value;
    };

    struct ProgramDiagnosticDataType 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         NodeId CreateSessionId;
         std::string CreateClientName;
         DateTime InvocationCreationTime;
         DateTime LastTransitionTime;
         std::string LastMethodCall;
         NodeId LastMethodSessionId;
         std::vector<Argument> LastMethodInputArguments;
         std::vector<Argument> LastMethodOutputArguments;
         DateTime LastMethodCallTime;
         StatusResult LastMethodReturnStatus;
    };

    struct Annotation 
    {
         uint8_t Encoding;
         ExpandedNodeId TypeId;
         int32_t BodyLength;
         std::string Message;
         std::string UserName;
         DateTime AnnotationTime;
    };

   }

} // namespace
    
